<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- header CSS -->
  <link rel="stylesheet" href="../css/header.css"/>
  
  </head>
  <style>
    .furniture:hover{
      opacity: 0.5;
    }
  </style>
  <script>
        var els = document.getElementsByClassName('color');
        for (var i = 0; i < els.length; i++) {
        els[i].onclick = fun1;
        }

        function fun1(e) {
        const overlay = document.getElementById("product-shape")
        console.log(overlay);
        var color=e.target.getAttribute("data-hex");
        console.log(color);
        overlay.style.fill=color;
        }
    

    function changeContent(){
      //main image
      document.getElementById("furnitureContent").innerHTML= "<div> <img src=\"https://image.ohou.se/i/bucketplace-v2-development/uploads/productions/158320065995789137.jpg?gif=1&w=1280&h=1280&c=c\" style=\"width:100%; display: block; \"> </div> <br/>";
      document.getElementById("furnitureContent").innerHTML+=" <div style=\"text-align: center; \"> <font color=\"black\" size=\"6\">"+"원목 책상 "+"<br> <font/></div>";
      document.getElementById("furnitureContent").innerHTML+= "</div>";

      // //color by option
      //     var min = 1,
      //     max = 3,
      //     select = document.getElementById('productColor');

      // for (var i = min; i<=max; i++){
      //     var opt = document.createElement('option');
      //     opt.value = i;
      //     opt.innerHTML = "pink";
      //     select.appendChild(opt);
      // }
      // document.getElementById('productColor').style.display="";

      //color by svg
      document.getElementById('productColor').innerHTML="<div class=\"color\" style=\"height: 30px; width: 30px; background-color: #e1e851; border-radius: 50%;\" data-hex=\"#e1e851\"></div>";
      document.getElementById('productColor').innerHTML+="<div class=\"color\" style=\"height: 30px; width: 30px; background-color: #8cd147; border-radius: 50%;\" data-hex=\"#8cd147\"></div>";
      document.getElementById('productColor').innerHTML+="<div class=\"color\" style=\"height: 30px; width: 30px; background-color: #4a9ccf; border-radius: 50%;\" data-hex=\"#4a9ccf\"></div>";
      }
      
  </script>

<script>
  var els = document.getElementsByClassName('color');
  for (var i = 0; i < els.length; i++) {
  els[i].onclick = fun1;
  }

  function fun1(e) {
  const overlay = document.getElementById("product-shape")
  console.log(overlay);
  var color=e.target.getAttribute("data-hex");
  console.log(color);
  overlay.style.fill=color;
  }
</script>

  <body>
      <div class="d-flex row col-sm-12 p-0 m-0" style="width: 100%; height: 100%;">
        <!-- <div>

        </div>
        <div style="background-color: #f1f3f5;">

        </div> -->

        <!-- Image Map Generated by http://www.image-map.net/ -->
        <div class="col-sm-9 p-0 m-0" style="height: 100%; width:100%; position: relative;">
          <img src="https://cdn-bhnll.nitrocdn.com/gSDMXibcJluvzIippFBvhCZIaoOxCvih/assets/static/optimized/rev-ccf470e/wp-content/uploads/handsome-study-interior-design-houston.png" width="100%" height="90%" usemap="#PYRoom" alt="" />
           <!-- <map name="PYRoom">
            <area target="" alt="" title="" href="http://naver.com" coords="659,854,1428,857,1473,906,1471,1336,1451,1345,1438,985,1057,982,1056,1334,1037,1342,1020,983,646,978,640,1332,623,1332,601,907" shape="poly">
            <area target="" alt="" title="" href="http://google.com" coords="941,765,1122,755,1135,850,942,848" shape="poly">        
            <area target="" alt="" title="" href="http://naver.com" coords="3,236,362,641" shape="rect">
               <area target="" alt="" title="" href="#" coords="1015,600,690,232" shape="rect">
              <area shape="poly" coords="864,668,912,650,922,668,971,667,973,718,981,722,985,729,988,731,1010,731,1010,742,833,742,833,730,865,730,865,721,874,721,874,718,864,668,864,668" href="#cn" title="Cartoon Network" alt="Cartoon Network" /> 
          </map> -->
         <div class="furniture" style="border-radius: 2rem; height: 2rem; width: 2rem; background-color: #ffb440; position: absolute; top: 37vh; left: 7vw;" onclick="changeContent()"></div>
         <div class="furniture" style="border-radius: 2rem; height: 2rem; width: 2rem; background-color: #ffb440; position: absolute; top: 60vh; left: 20vw;" onclick="changeContent()"></div>
         <div class="furniture" style="border-radius: 2rem; height: 2rem; width: 2rem; background-color: #ffb440; position: absolute; top: 60vh; left: 40vw; " onclick="changeContent()"></div>
         <header >
          <div style="background-color: black;">
              <div class="menu" style="height: max-content; ">
              <div><a href="#" class="menubtn">대기실</a></div>
              <div><a href="#" class="menubtn">상담실</a></div>
              <div><a href="#" class="menubtn">교정 진료실</a></div>
              <div><a href="#" class="menubtn">수술실</a></div>
              <div><a href="#" class="menubtn">소독실</a></div>
              <div><a href="#" class="menubtn">진료실</a></div>
              <div><a href="#" class="menubtn">수납실</a></div>
            </div>
          </div>
      </header>
        </div>
        <div class="col-sm-3 p-0 m-0" >
                <div class="card mb-2 box-shadow" style=" height: 100%;">
                    <div class="card-body my-5">
                      <h1 class="card-title pricing-card-title " style="text-align: center; font-weight: bold;"><font color="black" size="6">50PY 상담실 <br/></font></h1>
                      <ul class="list-unstyled mt-6 mb-4 " style="margin: 4rem; text-align: center;" >
                        <li id="furnitureContent">가구에 마우스를 올려<br/> 상세 정보를 확인해보세요</li>
                        <div id="productColor" class="row" style="height: 50px; width: 50px;"></div>
                         <div id = "productInfo"></div>
                      </ul>
                      <div style="bottom: 0px; position: absolute; bottom: 1vh; width: 90%; padding-right: 2rem; width: 100%; ">
                        <a type="button" class="btn btn-lg btn-block button" style="background-color:black; border-radius:2rem; font-weight: bold;" href="customerSupport""><font color="white" size="4">문의</font></a>
                        <div class="m-2" style="text-align: center;"><font size="1" color="gray">상품 디자인은 실제와 다를 수 있습니다</font></div>
                    </div>
                      </div>
                  </div>
            </div>
      </div>
      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>